In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df['EstimatedSalary']

0      19000
1      20000
2      43000
3      57000
4      76000
       ...  
395    41000
396    23000
397    20000
398    33000
399    36000
Name: EstimatedSalary, Length: 400, dtype: int64

In [4]:
def minmaxscaling(x):
  min_val = np.min(x)
  max_val = np.max(x)
  return (x-min_val)/(max_val-min_val)

In [5]:
df['scaled_salary'] = minmaxscaling(df['EstimatedSalary'])

In [6]:
df['scaled_salary'].min(), df['scaled_salary'].max()

(0.0, 1.0)

In [7]:
def stdscaling(x):
    mean_val=np.mean(x)
    std_val=np.std(x)
    return(x-mean_val)/(std_val)

In [8]:
df['scaled_std_salary']=stdscaling(df['EstimatedSalary'])

In [9]:
df

User ID  Gender  Age  EstimatedSalary  Purchased  scaled_salary  \
0    15624510    Male   19            19000          0       0.029630   
1    15810944    Male   35            20000          0       0.037037   
2    15668575  Female   26            43000          0       0.207407   
3    15603246  Female   27            57000          0       0.311111   
4    15804002    Male   19            76000          0       0.451852   
..        ...     ...  ...              ...        ...            ...   
395  15691863  Female   46            41000          1       0.192593   
396  15706071    Male   51            23000          1       0.059259   
397  15654296  Female   50            20000          1       0.037037   
398  15755018    Male   36            33000          0       0.133333   
399  15594041  Female   49            36000          1       0.155556   

     scaled_std_salary  
0            -1.490046  
1            -1.460681  
2            -0.785290  
3            -0.374182  
4             0.183751  
..                 ...  
395          -0.844019  
396          -1.372587  
397          -1.460681  
398          -1.078938  
399          -0.990844  

[400 rows x 7 columns]

In [10]:
df['scaled_std_salary'].mean(), df['scaled_std_salary'].std()

(-1.7763568394002505e-17, 1.0012523486435179)

In [11]:
round(df['scaled_std_salary'].mean()),round(df['scaled_std_salary'].std())

(0, 1)

In [12]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [13]:
mmx=MinMaxScaler()


In [14]:
std=StandardScaler()

In [15]:
x=df[['EstimatedSalary']]
mmx.fit_transform(x)

array([[0.02962963],
       [0.03703704],
       [0.20740741],
       [0.31111111],
       [0.45185185],
       [0.31851852],
       [0.51111111],
       [1.        ],
       [0.13333333],
       [0.37037037],
       [0.48148148],
       [0.27407407],
       [0.52592593],
       [0.02222222],
       [0.4962963 ],
       [0.48148148],
       [0.07407407],
       [0.08148148],
       [0.0962963 ],
       [0.1037037 ],
       [0.05185185],
       [0.25185185],
       [0.19259259],
       [0.05185185],
       [0.05925926],
       [0.03703704],
       [0.0962963 ],
       [0.11111111],
       [0.20740741],
       [0.02222222],
       [0.43703704],
       [0.9037037 ],
       [0.00740741],
       [0.21481481],
       [0.55555556],
       [0.08888889],
       [0.0962963 ],
       [0.25185185],
       [0.42222222],
       [0.11851852],
       [0.01481481],
       [0.26666667],
       [0.68888889],
       [0.        ],
       [0.51111111],
       [0.03703704],
       [0.47407407],
       [0.288

In [16]:
std.fit_transform(x)

array([[-1.49004624],
       [-1.46068138],
       [-0.78528968],
       [-0.37418169],
       [ 0.18375059],
       [-0.34481683],
       [ 0.41866944],
       [ 2.35674998],
       [-1.07893824],
       [-0.13926283],
       [ 0.30121002],
       [-0.52100597],
       [ 0.47739916],
       [-1.51941109],
       [ 0.35993973],
       [ 0.30121002],
       [-1.3138571 ],
       [-1.28449224],
       [-1.22576253],
       [-1.19639767],
       [-1.40195167],
       [-0.60910054],
       [-0.84401939],
       [-1.40195167],
       [-1.37258681],
       [-1.46068138],
       [-1.22576253],
       [-1.16703281],
       [-0.78528968],
       [-1.51941109],
       [ 0.12502088],
       [ 1.97500684],
       [-1.5781408 ],
       [-0.75592482],
       [ 0.59485858],
       [-1.25512738],
       [-1.22576253],
       [-0.60910054],
       [ 0.06629116],
       [-1.13766796],
       [-1.54877595],
       [-0.55037082],
       [ 1.123426  ],
       [-1.60750566],
       [ 0.41866944],
       [-1

In [17]:
x=df[['Age', 'EstimatedSalary']].values
y = df['Purchased'].values

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2,random_state=0)

In [19]:
x_test

array([[    30,  87000],
       [    38,  50000],
       [    35,  75000],
       [    30,  79000],
       [    35,  50000],
       [    27,  20000],
       [    31,  15000],
       [    36, 144000],
       [    18,  68000],
       [    47,  43000],
       [    30,  49000],
       [    28,  55000],
       [    37,  55000],
       [    39,  77000],
       [    20,  86000],
       [    32, 117000],
       [    37,  77000],
       [    19,  85000],
       [    55, 130000],
       [    35,  22000],
       [    35,  47000],
       [    47, 144000],
       [    41,  51000],
       [    47, 105000],
       [    23,  28000],
       [    49, 141000],
       [    28,  87000],
       [    29,  80000],
       [    37,  62000],
       [    32,  86000],
       [    21,  88000],
       [    37,  79000],
       [    57,  60000],
       [    37,  53000],
       [    24,  58000],
       [    18,  52000],
       [    22,  81000],
       [    34,  43000],
       [    31,  34000],
       [    49,  36000],


In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [21]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [22]:
knn.score(x_test,y_test)


0.8375

In [23]:
sal_scaler=MinMaxScaler()

In [24]:
df_x_train=pd.DataFrame(x_train)

In [25]:
df_x_train

0       1
0    58  144000
1    59   83000
2    24   55000
3    26   35000
4    58   38000
..   ..     ...
315  48   30000
316  29   43000
317  36   52000
318  27   54000
319  26  118000

[320 rows x 2 columns]

In [26]:
df_x_train['sc_sal'] = sal_scaler.fit_transform(df_x_train[[1]])

In [28]:
x_train_scaled=df_x_train[[0,'sc_sal']].values

In [29]:
df_x_test = pd.DataFrame(x_test)
df_x_test['sc_sal'] = sal_scaler.transform(df_x_test[[1]])
x_test_scaled = df_x_test[[0, 'sc_sal']].values

In [30]:
knn.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [31]:
knn.score(x_test_scaled,y_test)

0.925